### ISSUE TITLE
Criar rotas post e get

### ISSUE THREAD

**Issue by pereiraIgor** [AramisAraujo/PicoriMori#8]
Não consegui achar as rotas do backend (possivelmente confusão minha), baixei teu projeto mas não consegui fazer requisições nele.Se possível, criar um readme mostrando o comportamento das rotas, e como fazer para rodar seu projeto da mesma maneira que você está rodando

**Comment by matheusgr** [comment]
@pereiraIgor O sistema faz uso de graphqle, nesse sentido, @AramisAraujo não precisa definir GET/POST, mas consultas e mutations.

Recomendo fechar a issue como atendida.
